task:
  class: IndustRealTaskInsert

goals:
  source: guide  # options: random, perception, guide
  random:
    num_goals: null
    bounds: null
  perception:  # currently used for pick-place-insert sequence
  config: perception.yaml
    selectors: ['2_prong_receptacle', '3_prong_receptacle']  # detections to select for task
    goal_heights:
      2_prong_receptacle: 0.0947
      3_prong_receptacle: 0.0898
    goal_lateral_offsets: null
  guide:
    xy_perturbation: null
    z_perturbation: null
    yaw_perturbation: null

motion:
  source: rl  # options: rl, frankapy, libfranka, frankapy_and_libfranka
  duration: 20.0
  do_before: ['close_gripper']  # options: open_gripper, close_gripper, go_upward, go_downward, go_home
  do_after: ['open_gripper', 'go_upward', 'go_home']

rl:
  checkpoint_name: industreal_policy_insert_pegs
  policy_eval_freq: 60.0
  pos_err_thresh: 0.001  # position threshold below which to terminate early
  ori_err_rad_thresh: 0.0873  # orientation threshold below which to terminate early
  observation_noise_pos: null
  override_obs_goal_roll_angle: True  # override observed goal roll angle to 0.0 (instead of pi)

control:
  prop_gains: [1000, 1000, 100, 50, 50, 50]
  # NOTE: deriv_gains computed automatically as 2 * sqrt(prop_gains)
  mode:
    type: leaky_plai  # options: nominal, plai, leaky_plai
    nominal:
      action_scale: null
    plai:
      action_scale: null
    leaky_plai:
      action_scale: [0.0004, 0.0004, 0.0004, 0.001, 0.001, 0.001]
      pos_err_thresh: [0.04, 0.04, 0.05]