task:
  class: IndustRealTaskInsert

goals:
  source: guide  # options: random, perception, guide
  random:
    num_goals: null
    bounds: null
  perception:  # currently used for pick-place-insert sequence
    config: perception.yaml
    selectors: ['round_hole', 'rect_hole']  # detections to select for task
    goal_heights:
      round_hole: 0.0811
      rect_hole: 0.0811
    goal_lateral_offsets: null
  guide:  # currently used for standalone insert task
    xy_perturbation: 0.010
    z_perturbation: [0.035, 0.045]  # bottom of peg should be 10-20 mm above hole
    yaw_perturbation: [-0.0873, 0.0873]

motion:
  source: rl  # options: rl, frankapy, libfranka, frankapy_and_libfranka
  duration: 20.0
  do_before: ['close_gripper']  # options: open_gripper, close_gripper, go_upward, go_downward, go_home
  do_after: ['open_gripper', 'go_upward', 'go_home']

rl:
  checkpoint_name: industreal_policy_insert_pegs
  policy_eval_freq: 60.0
  pos_err_thresh: 0.001  # position threshold below which to terminate early
  ori_err_rad_thresh: 0.0873  # orientation threshold below which to terminate early
  observation_noise_pos: [0.002, 0.002, 0.0]  # half-amplitude
  override_obs_goal_roll_angle: True  # override observed goal roll angle to 0.0 (instead of pi)

control:
  prop_gains: [1000, 1000, 100, 50, 50, 50]
  # NOTE: deriv_gains computed automatically as 2 * sqrt(prop_gains)
  mode:
    type: leaky_plai  # options: nominal, plai, leaky_plai
    nominal:
      action_scale: null
    plai:
      action_scale: null
    leaky_plai:
      action_scale: [0.0006, 0.0006, 0.0004, 0.001, 0.001, 0.001]
      pos_err_thresh: [0.05, 0.05, 0.03]